### ISSUE TITLE
lion如何实现Zero allocations

### ISSUE THREAD

**Issue by meilihao** [celrenheit/lion#1]

**Comment by JohnSmithX** [comment]
Implement it with sync.Pool and [view](https://github.com/celrenheit/lion/blob/master/router.go#L263-L273)

**Comment by meilihao** [comment]
我在自己写的web框架里也使用了sync.Pool还是做不到零分配,但分配的次数比没使用前有所减少.
如何才能实现零分配,或者如何查找哪些地方出现了分配?

**Comment by JohnSmithX** [comment]
sync.Pool doc:
> Any item stored in the Pool may be removed automatically at any time without notification. If the Pool holds the only reference when this happens, the item might be deallocated.
