### ISSUE TITLE
Support FastHTTP as well

### ISSUE THREAD

**Issue by thedrow** [celrenheit/lion#2]
[FastHTTP](https://github.com/valyala/fasthttp) is a much faster HTTP library for Go.
Echo v2 already supports it.
It'd be nice to have it in other frameworks as well.

**Comment by celrenheit** [comment]
FastHTTP is a great project in terms of speed and memory allocation but it will not be supported for the moment (maybe for a v2). Lion is centered around `lion.Handler` interface and is built for net/http.
