### ISSUE TITLE
Benchmarks results

### ISSUE THREAD

**Issue by goc0der** [celrenheit/lion#4]
Hello, I just released that you don't have full benchmark results, I have created a repository, as new gopher which I ran the benchmark and compare all frameworks here [https://github.com/goc0der/go-http-routing-benchmark](https://github.com/goc0der/go-http-routing-benchmark), can you provide the link to your README or should I PR ?

**Comment by celrenheit** [comment]
Thank you. Could you please add lion to the benchmarks before I merge your PR ?

**Comment by goc0der** [comment]
@celrenheit  Yes Sorry I though I did it but they're so many I do it today and I will re-pull

**Comment by celrenheit** [comment]
@goc0der Any progress on these benchmarks ?
