### ISSUE TITLE
label: question Serving static files

### ISSUE THREAD

**Issue by agaviria** [celrenheit/lion#6]
@celrenheit  What would be the simplest form to serve static files with Lion?  I'm attempting to get the following folders "css", "js", "img", and "templates" all within a root folder named "public".
`
for _, dir := range []string{"js", "css", "img", "templates"} {
	lion.ServeFiles(fmt.Sprintf("/%s/", dir))
}
`

**Comment by celrenheit** [comment]
Hello @agaviria,

I just fixed an issue with ServeFiles. Now you can do something like this:

```go
l := lion.New()

for _, dir := range []string{"js", "css", "img", "templates"} {
	base := fmt.Sprintf("/%s", dir)
	dirbase := fmt.Sprintf("./public/%s", dir)

	l.ServeFiles(base, http.Dir(dirbase))
}

l.Run()
```

Note that there is still some work to do with static file serving.
Hope this helps.
