### ISSUE TITLE
Working with Request Body and Query Params.

### ISSUE THREAD

**Issue by whitebook** [celrenheit/lion#7]
I was trying your framework. 

Could you provide examples of you access the body for a Post or Put request?

As well getting URL params from a Get request?

Thanks.

**Comment by celrenheit** [comment]
Hello @whitebook,

You can access the body of a pull request as you would do with native http Handlers. You can use for example [ioutil.ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll).
Here is a simple example with a url parameter "to" and the sender's email is passed in the request's body with his password.

```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/celrenheit/lion"
	"golang.org/x/net/context"
)

func main() {
	l := lion.Classic()
	l.GetFunc("/send_mail/:to", handler)
	l.PostFunc("/send_mail/:to", handler)
	l.Run()
}

type user struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func handler(c context.Context, w http.ResponseWriter, r *http.Request) {
	// Access url params
	to := lion.Param(c, "to")

	// Reading from body and decoding json
	var u user
	defer r.Body.Close()
	json.NewDecoder(r.Body).Decode(&u)
	fmt.Println("Received password:", u.Password)
	fmt.Fprintf(w, "Sending mail to %s from %s", to, u.Email)
}
```

You can test this using curl:

```
curl -XPOST -d '{"email":"from@test.com", "password": "pass"}' -H "Content-type: application/json" http://localhost:3000/send_mail/to@test.com
```

Change -XPOST to -XGET to test out the get request.

Hope this answers your questions.

**Comment by whitebook** [comment]
Thanks. I think that helps.
