### ISSUE TITLE
"color" dependancy

### ISSUE THREAD

**Issue by everdev** [celrenheit/lion#9]
```
go get github.com/celrenheit/lion
# github.com/celrenheit/lion
../../celrenheit/lion/middlewares.go:20: undefined: color.FgHiMagenta
../../celrenheit/lion/middlewares.go:24: undefined: color.FgHiBlue
../../celrenheit/lion/middlewares.go:25: undefined: color.FgHiGreen
```

might want to vendor, or add to the docs

**Comment by celrenheit** [comment]
Which go version / OS are you using ?
I tried to reproduce the error with `go get github.com/celrenheit/lion` but it seems to work fine.
Yes, I am going to vendor them to avoid these kind of issues or any version incompatibility problems.

**Comment by everdev** [comment]
go version go1.6 darwin/amd64

**Comment by celrenheit** [comment]
Thank you for the feedback.
Does the last commit solves your issue ?

**Comment by celrenheit** [comment]
It creates a different issue when vendoring `golang.org/x/net/context` and used outside of this library:
```
cannot convert func literal (type func("golang.org/x/net/context".Context, http.ResponseWriter, *http.Request)) to type lion.HandlerFunc
```
So I am going to remove golang.org/x/net/context from the vendor folder (more info [here](https://groups.google.com/forum/#!msg/golang-nuts/AnMr9NL6dtc/o9VumsIOCAAJ)) and document it in the README.md
